"""Create document_images

Revision ID: 55e72db8d9be
Revises: 0dc81b10c7b0
Create Date: 2022-05-19 23:28:58.620601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e72db8d9be'
down_revision = '0dc81b10c7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
